export const UNIT = {
    CELSIUS: "CELSIUS",
    FARENHEIT: "FARENHEIT",
    ACCELETATION: "ACCELETATION",
    ANGULAR_ACCELETATION: "ANGULAR ACCELETATION"
  };
  
export const UNIT_CAPTION = {
  [UNIT.CELSIUS]: "°C",
  [UNIT.FARENHEIT]: "°F",
  [UNIT.ACCELETATION]: "m/s²",
  [UNIT.ANGULAR_ACCELETATION]: "rad/s²"
};
  
export const INDEX_POSITION = {
    RIGHT_TOP: "RIGHT_TOP",
    RIGHT_BOTTOM: "RIGHT_BOTTOM",
    RIGHT_CENTER: "RIGHT_CENTER"
};